<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testing.txt</name>
   <tag></tag>
   <elementGuidId>6ba80396-3686-4871-921c-e130f0edb57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploaded-files</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uploaded-files']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b516574-52cb-4c95-9fff-fc108aebce31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploaded-files</value>
      <webElementGuid>260fb78e-14a5-4896-894b-3b48b46ce1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel text-center</value>
      <webElementGuid>2be9da3e-f521-470e-8eb3-8bee4a4b463a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    testing.txt
  </value>
      <webElementGuid>5d5998c3-bfdb-4372-9f1a-7e57a709f38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploaded-files&quot;)</value>
      <webElementGuid>52115e3a-923b-4fbb-93ac-684754d3d7c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uploaded-files']</value>
      <webElementGuid>db4522ec-e83a-4b7a-b7f6-477497011e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>fcdb3fe8-8cd6-45b6-b212-a77d81a72e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploaded!'])[1]/following::div[1]</value>
      <webElementGuid>c54ae912-5bbf-442c-ad3e-f51c8a0ce2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::div[1]</value>
      <webElementGuid>4e50bc04-bd7d-47df-902e-fa5b38e97466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testing.txt']/parent::*</value>
      <webElementGuid>0231fe86-6283-4145-9f77-30cf93024d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>cdb0bfcf-44d4-4d53-a187-8136bd172af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uploaded-files' and (text() = '
    testing.txt
  ' or . = '
    testing.txt
  ')]</value>
      <webElementGuid>53b4087e-2b09-48cd-b0fe-80ce13fdd867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
